#!/usr/bin/env bash

# ./0-transfer_file README.md 54.237.106.126 ubuntu ~/.ssh/id_rsa
# PATH_TO_FILE=$1
# IP=$2
# USERNAME=$3
# PATH_TO_SSH_KEY=$4

if [ $# -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"

else
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~/
fi
