#!/usr/bin/env bash

# App name to be installed
app_name="nginx"
listen_port="/etc/nginx/sites-enabled/default"
nginx_page="/var/www/html/index.nginx-debian.html"

# Check if the app is installed
if command -v "$app_name" >/dev/null 2>&1; then
    # echo "$app_name is installed.
    :
else
    # echo "$app_name is not installed. Installing..."
    sudo apt install nginx
fi

# Give full permissions
sudo chmod 777 "$listen_port"
sudo chmod 777 "$nginx_page"

# Overwrite landing page
echo "Hello World!" > "$nginx_page"