#!/usr/bin/env bash
# script to install and configure haproxy as a load balancer
# Distribute requests using a roundrobin algorithm
# Make sure that HAproxy can be managed via an init script

sudo apt-get upgrade -y
sudo apt-get install haproxy -y

echo "ENABLED=1" >> /etc/default/haproxy

echo "frontend http_front
bind *:80
mode http
default_backend http_back

backend http-back
balance roundrobin
server 134677-web-01 154.237.106.126:80 check
server 134677-web-02 54.175.223.76:80 check " > /etc/haproxy/haproxy.cfg

sudo service haproxy restart