#!/usr/bin/env bash
# Install and configure HAproxy

sudo apt-get update
sudo apt-get install haproxy=2.0.\*

config_file="/etc/haproxy/haproxy.cfg"

# Check if the file exists
if [ -f "$config_file" ]; then
    {
        echo "frontend http"
        echo "    bind *:80"
        echo "    default_backend servers"
        echo ""
        echo "backend servers"
        echo "    balance roundrobin"
        echo "    server 134677-web-01 54.237.106.126:80 check"
        echo "    server 134677-web-02 54.175.223.76:80 check"
    } >> "$config_file"
    echo "Lines appended to $config_file"
else
    echo "File $config_file does not exist."
fi

sudo service haproxy restart
