#!/usr/bin/env bash

# Define the private key file path
private_key=~/.ssh/school

# Define the username and hostname
username=ubuntu
hostname=54.237.106.126  # Replace with your server's IP address

# Connect to the server using SSH with the private key
ssh -i "$private_key" "$username@$hostname"

# Optionally, you can add commands to run on the server after connecting, if needed
# For example:
# ssh -i "$private_key" "$username@$hostname" "echo 'Connected to the server'; uptime"

# Note: Replace '54.157.161.128' with your actual server's IP address
